name: consult_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  go_router:
  flutter_screenutil:
  flutter_svg:
  bloc:
  flutter_bloc:
  flutter_localization:
  dio:
  retrofit:
  get_it:
  injectable:
  logger:
  json_annotation:
  awesome_dialog:
  cached_network_image:
  pin_code_fields:
dev_dependencies:
  injectable_generator:
  build_runner:
  retrofit_generator:
  json_serializable:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/svg/icons/
    - assets/images/png/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
